apiVersion: v1
kind: Pod
metadata:
  name: {{ .app.Name }}-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLables:
      app: {{ .app.Name }}
  template:
    metadata:
      lables:
        app: {{ .app.Name }}
    spec:
      containers:
        - name: {{ .app.Name }}
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}

